### ISSUE TITLE
Deprecate depject: tracking issue

### ISSUE THREAD

**Issue by black-puppydog** [ssbc/patchwork#1400]
There are many files that have to be tackled here, and I think it'd be good to have a handy list of them.
So let's run `for l in $(rg -c 'gives =' | cut -d ':' -f 1); do echo "- [ ] $l"; done` and see.
All of these live in `lib/depject` of course.

- [ ] progress/obs.js
- [ ] tag/async/suggest.js
- [ ] tag/html/tag.js
- [x] progress/html/render.js
- [ ] progress/html/peer.js
- [ ] feed/html/follow-warning.js
- [ ] feed/html/rollup.js
- [ ] feed/html/meta-summary.js
- [ ] blob/obs/has.js
- [ ] blob/sync/url.js
- [ ] feed/obs/recent.js
- [ ] intl/sync/i18n.js
- [x] app/fullscreen.js
- [ ] app/link-preview.js
- [x] app/views.js
- [ ] message/async/name.js
- [ ] message/async/publish.js
- [ ] message/obs/author.js
- [ ] message/obs/name.js
- [x] app/sync/external-handler/git.js
- [ ] message/obs/likes.js
- [ ] message/obs/get.js
- [ ] message/sheet/preview.js
- [ ] message/html/compose.js
- [ ] message/html/forks.js
- [ ] message/html/render/vote.js
- [ ] message/html/render/issue.js
- [ ] message/html/render/about.js
- [ ] message/html/render/blog.js
- [ ] message/html/render/channel.js
- [ ] message/html/render/zzz-fallback.js
- [ ] app/html/search.js
- [ ] message/html/render/post.js
- [ ] message/html/render/attending.js
- [ ] message/html/render/made-changes.js
- [ ] message/html/link.js
- [ ] message/html/render/gathering.js
- [ ] message/html/references.js
- [ ] message/html/missing.js
- [ ] message/html/render/following.js
- [ ] message/html/actions.js
- [ ] app/html/progress-notifier.js
- [x] message/html/timestamp.js
- [ ] message/html/markdown.js
- [ ] message/html/layout/mini.js
- [ ] message/html/layout/default.js
- [ ] message/html/metas.js
- [ ] suggest.js
- [x] message/html/decorate/context-menu.js
- [ ] about/obs.js
- [ ] invite/invite.js
- [ ] sheet/profiles.js
- [x] sheet/display.js
- [ ] sheet/editTags.js
- [ ] sheet/tags/tags.js
- [ ] about/async/latest-values.js
- [ ] sheet/tags/renderTags.js
- [ ] profile/async/suggest.js
- [ ] gathering/sheet/edit.js
- [ ] profile/sheet/edit.js
- [ ] profile/html/preview.js
- [ ] sheet/tags/renderTaggers.js
- [ ] profile/async/avatar.js
- [ ] invite/sheet.js
- [ ] profile/html/person.js
- [ ] keys.js
- [ ] sbot.js
- [ ] profile/obs/rank.js
- [ ] profile/obs/contact.js
- [ ] profile/obs/recently-updated.js
- [ ] backlinks/obs.js
- [ ] about/html/image.js
- [ ] about/html/link.js
- [ ] channel/html/preview.js
- [x] channel/html/link.js
- [x] channel/sync/normalize.js
- [ ] channel/obs/subscribed.js
- [ ] channel/html/subscribe-toggle.js
- [ ] channel/obs/recent.js
- [ ] contact/async.js
- [ ] channel/obs/subscribers.js
- [ ] contact/obs.js
- [ ] channel/async/suggest.js
- [x] message/sync/root.js
- [ ] message/sync/unbox.js
- [ ] page/html/render/public.js
- [ ] page/html/render/private.js
- [ ] page/html/render/mentions.js
- [ ] page/html/render/channel.js
- [ ] page/html/render/attending-gatherings.js
- [ ] page/html/render/tag.js
- [ ] page/html/render/all.js
- [ ] page/html/render/search.js
- [ ] page/html/render/settings.js
- [ ] page/html/render/profile.js
- [ ] page/html/render/your-posts.js
- [ ] page/html/render/participating.js
- [ ] page/html/render/gatherings.js
- [ ] page/html/render/message.js
- [ ] page/html/render/channels.js
- [ ] contact/html/follow-toggle.js
- [x] message/sync/timestamp.js

**Comment by black-puppydog** [comment]
I was stuck on this, but during the electron bump works, I stumbled over one thing that might help:

[`patch-settings`](https://github.com/mixmix/patch-settings) is at least one dependency that actually a depject module.
According to [the docs](https://github.com/ssbc/patchwork/blame/master/docs/CONTRIBUTING.md#L54) it is also the *only* dependency to hook into depject (to be verified). 

Removing this dependency (by inlining or refactoring) should be easy, and break very little since it is only used in patchwork and patchbay. With the latter being unmaintained we can probably "move fast and break things" here. Once this is done, `lib/depject/intl/sync/i18n.js` and then `lib/depject/page/html/render/settings.js` should become unblocked for dep-ejection. 🙂
