### ISSUE TITLE
Public Beta Roadmap

### ISSUE THREAD

**Issue by pfrazee** [ssbc/patchwork#308]
Patchwork & Scuttlebot
- [ ] Frontend tests
- [ ] Reliable file-sharing
- [ ] Network IO measurement
- [ ] Memory/CPU/bandwidth reduction
- [ ] Performant local search
- [ ] Effective moderation tools
- [ ] UI / API polish
- [ ] Live help
- [ ] Testing & debugging tools for application developers

Website / Docs / Branding
- [ ] Patchwork logo
- [ ] Finish site aesthetic and layout
- [ ] Patchwork page
- [ ] Blog page
- [ ] Team page
- [ ] Guide: Running Patchwork privately from a server
- [ ] Guide: Running a Pub
- [ ] Guide: Writing an SSB application
- [ ] Guide: Integrating Scuttlebot into an existing Web service
- [ ] Guide: Message schemas and SSB best practices
- [ ] Guide: Using Secret Stack
- [ ] Guide: Using MuxRPC
- [ ] Guide: Using Pull Streams
- [ ] Complete SSB description
- [ ] Complete MuxRPC description
- [ ] Complete Secret-Handshake description
- [ ] Complete Private-Box description
- [ ] Complete API reference

Packaging

- [ ] Windows Installer
- [ ] [Windows Autoupdate](/ssbc/patchwork-electron/issues/8)
- [ ] OSX Installer
- [ ] [OSX Autoupdate](/ssbc/patchwork-electron/issues/9)
- [ ] Linux Installer
- [ ] Linux Autoupdate

**Comment by mixmix** [comment]
Nice. I think there's a bunch of details that could be interpreted. Lets treat this as something to reference back to and continue to discuss. Thanks for pulling this together @pfraze

**Comment by pfraze** [comment]
We should create issues for individual items and link to them from here

**Comment by dominictarr** [comment]
please add: running scuttlebot as a test network

**Comment by pfraze** [comment]
I added "Testing & debugging tools for application developers"

**Comment by mmckegg** [comment]
With #423 looming doesn't seem relevant anymore. Closing!
