### ISSUE TITLE
Dark Crystal Integration - Phase 1

### ISSUE THREAD

**Issue by kyphae** [ssbc/patchwork#952]
Shard and share your `.ssb/secret` and your `gossip.json` directly in Patchwork. As discussed with @mmckegg, this will be a 3 phase integration, allowing users to:

- (a) backup their identity with their peers
- (b) reclaim their old identity from their custodians using a newly generated identity after it has been lost (lost / broken laptop).
- (c) restart Patchwork as the new identity, which automates reintegrating the recovered identity. Gives the user the option to remove or backup the identity in use.

# Phase 1

**Backup your identity with your peers**

### Backend
* [x] Extend the `shard` schema to accept a blob reference to `gossip.json` file in [`ssb-dark-crystal-schema`](https://github.com/blockades/ssb-dark-crystal-schema)
* [x] Extend the `shard` publish action params in [`scuttle-dark-crystal`](https://github.com/blockades/scuttle-dark-crystal) to accept a blob reference
* [x] Ensure the file is encrypted when creating a dark crystal

### UI
* [x] Draw some wireframes and run them by @mmckegg (upload here...)
* [x] CSS! Consult Matt to make sure it fits with Patchwork's overall style

#### Required functionality
* [x] Add a `Back up` button to the `/settings` page which:
* [x] Opens a modal containing a form that takes 2 inputs: a list of custodians and a quorum
* [x] Form submission performs the following
  * [x] Load the entire `.ssb/secret` and stringify the JSON - this is the secret
  * [x] Load, encrypts and generate a blob ID for the `gossip.json` file
  * [x] Uses `scuttle-dark-crystal` to publish the message with `SSB Identity` as the `name`.
* [x] Add details about any existing backup so users can see that they've successfully backed up their identity - current custodians and the quorum required.

### Backlinks:
Phase 2 - https://github.com/ssbc/patchwork/issues/953
Phase 3 - https://github.com/ssbc/patchwork/issues/954

**Comment by ameba23** [comment]
@KGibb8 

> Extend the root or the ritual schema to accept a blob reference to gossip.json file in ssb-dark-crystal-schema

This excites me, as allowing bigger secrets by using blobs is something we've often talked about but never managed to make happen.  and i think it would be a great feature to have.

But i would argue that since the purpose of this design is account recovery, there's not much point in referencing the blob in the root or ritual message, since they can only be seen by the owner of the secret.

i would propose the blob reference should either be included in each shard message, or be included in the secret itself.  

including it in the secret would give greater security, as no individual custodian would know where it was, but at the cost of making it more difficult to replicate and 'health check' that it is still being held somewhere. so i think the best option would be to keep it in the shard messages.

**Comment by KGibb8** [comment]
@ameba23 oh I was sure I rewrote that to say it _has_ to be part on the shard. I think I mentioned this in the chat we had. Thanks for pointing out here.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 800.0 DAI (800.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ssbc/patchwork/952/2636).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/ssbc/patchwork/952/2636).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $49,277.53 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 2 months, 4 weeks from now.
Please review their action plans below:


**1) [gutsal-arsen](https://gitcoin.co/profile/gutsal-arsen) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/ssbc/patchwork/952/2636?mutate_worker_action=approve&worker=gutsal-arsen) | [reject worker](https://gitcoin.co/issue/ssbc/patchwork/952/2636?mutate_worker_action=reject&worker=gutsal-arsen))_.**

Forked [ssbc/patchwork](https://github.com/ssbc/patchwork)

Going to fork both: [blockades/scuttle-dark-crystal](https://github.com/blockades/scuttle-dark-crystal) and [blockades/ssb-dark-crystal-schema](https://github.com/blockades/scuttle-dark-crystal) to be able to merge PR [52](https://github.com/blockades/scuttle-dark-crystal/pull/52) and PR [20](https://github.com/blockades/ssb-dark-crystal-schema/pull/20) respectively. 

Add tests.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ssbc/patchwork/952/2636).

**Comment by KGibb8** [comment]
for wireframes see https://github.com/ssbc/patchwork/issues/953#issuecomment-474927844

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=1) | [3 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=3) | [5 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=5) | [10 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=10) | [100 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=100)

**Comment by KGibb8** [comment]
@gitcoinbot see PR https://github.com/ssbc/patchwork/pull/976

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=1) | [3 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=3) | [5 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=5) | [10 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=10) | [100 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=100)

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=1) | [3 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=3) | [5 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=5) | [10 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=10) | [100 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=100)

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=1) | [3 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=3) | [5 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=5) | [10 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=10) | [100 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=100)

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=1) | [3 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=3) | [5 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=5) | [10 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=10) | [100 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=100)

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=1) | [3 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=3) | [5 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=5) | [10 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=10) | [100 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=100)

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=1) | [3 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=3) | [5 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=5) | [10 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=10) | [100 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=100)

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=1) | [3 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=3) | [5 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=5) | [10 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=10) | [100 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=100)

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=1) | [3 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=3) | [5 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=5) | [10 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=10) | [100 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=100)

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=1) | [3 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=3) | [5 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=5) | [10 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=10) | [100 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=100)

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=1) | [3 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=3) | [5 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=5) | [10 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=10) | [100 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=100)

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=1) | [3 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=3) | [5 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=5) | [10 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=10) | [100 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=100)

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=1) | [3 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=3) | [5 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=5) | [10 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=10) | [100 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=100)

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=1) | [3 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=3) | [5 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=5) | [10 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=10) | [100 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=100)

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=1) | [3 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=3) | [5 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=5) | [10 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=10) | [100 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=100)

**Comment by KGibb8** [comment]
@gitcoinbot this issue is completed. See https://github.com/ssbc/patchwork/pull/985

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=1) | [3 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=3) | [5 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=5) | [10 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=10) | [100 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=100)

**Comment by gitcoinbot** [comment]
@kgibb8 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=1) | [3 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=3) | [5 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=5) | [10 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=10) | [100 days](https://gitcoin.co/issue/ssbc/patchwork/952/2636?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 800.0 DAI (800.0 USD @ $1.0/DAI) has been submitted by__:

 1. [@kgibb8](https://gitcoin.co/profile/kgibb8)



@ceresstation please take a look at the submitted work:
* [PR](https://github.com/ssbc/patchwork/pull/985) by @KGibb8

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ssbc/patchwork/952/2636)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/ssbc/patchwork/952/2636).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $96,345.39 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 800.0 DAI (800.0 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @KGibb8.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ssbc/patchwork/952/2636)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $98,141.27 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
